# Generated by Django 2.2.7 on 2022-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='budgetinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Groceries'), (2, 'Cleaning products'), (3, 'Cosmetics'), (4, 'Beauty'), (5, 'Entertainment'), (6, 'Children'), (7, 'Transport'), (8, 'Education'), (9, 'Bills'), (10, 'Clothing'), (11, 'Health'), (12, 'Alcohol'), (13, 'Wine'), (14, 'Cigarettes'), (15, 'Taxes'), (16, 'Accomodation'), (17, 'Home'), (18, 'Electronics'), (19, 'Sport'), (20, 'Culture'), (21, 'Investment'), (22, 'Other')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
